version: '2'
services:
  nginx:
    image: evild/alpine-nginx:1.11.2-libressl
    restart: always
    volumes:
      - .:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 9980:80
      - 9443:443
  php:
    build: ./php #evild/alpine-wordpress:4.5.3
    restart: always
    volumes:
      - .:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=SecrPassword
  db:
    image: mariadb:10
    restart: always
    volumes:
      - /tmp/wordpress-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SecrPassword

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
